version: '2.1'
services:
  site:
    image: "lopydev/php-7.2-cli-stretch"
    container_name: "dev_sharedsway_http"
    env_file:
      - .env
    volumes:
      - app:/app
    expose:
      - 50010
    ports:
      - 0.0.0.0:50010:50010
    user: "debian"
    working_dir: '/app'
    command: ["php","example/03.server.start.php"]
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind